# Site settings
title: 清风徐来
SEOTitle: 清风徐来
header-img: img/wallhaven-8ody32.jpg
email: 暂无
description: "欢迎大家访问，一起交流学习."
keyword: "徐"
url: "http://jeffxjh.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/jeffxjh/jeffxjh.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "susan"
sidebar-avatar: /img/wallhaven-y8vvex.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     暂无
zhihu_username:     小可爱
github_username:    xiaokeai18
facebook_username:  暂无
jianshu_username:   暂无
#twitter_username:   暂无




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
#redcarpet:
#    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
kramdown:
  input: GFM                            # use Github Flavored Markdown !important




# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 6cbaa4389d74519e2e52                            #生成的clientID
  clientSecret: 9ad60699b9b111d887b1510d34418901ca1a0db2    #生成的clientSecret
  repo: xiaokeai18.github.io    #仓库名称
  owner: xiaokeai18    #github用户名
  admin: xiaokeai18
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: e9f1f0510e25f0b8fda63db0dbae8794
# Google Analytics
ga_track_id: 'UA-132855876-1'            # Format: UA-xxxxxx-xx
ga_domain: wangpei.ink               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    }
]
